### PR TITLE
Added the scripts to record the execution times for the different Broadcasting implementations

### PR DESCRIPTION
**Pull request by HeshamElsaman**
Added the scripts to record the execution times for the different implementations of Broadcasting in the multiplication of a square matrix by either a scalar or another square matrix.

### CODE REVIEW

**Comment by kylemasc917** [comment]
@abruns123 I have added you as reviewer

**Comment by HeshamElsaman** [comment]
Yeah this error was noticed and fixed in a following pull request

**Review by abruns123 — APPROVED** [review]
Alright, as the error is fixed in another pull request, it should be fine to merge this. Might be better for the future to fix errors within a pull request via commits so that reviewers don't have to check other pull requests.

**Comment by HeshamElsaman** [comment]
Yeah agreed. It just slipped :"

**Pull request merged**
