### PR TITLE
Diagonal return - Manual implementation added

### PR DESCRIPTION
**Pull request by avgagliardo**
added a custom method for get_diagonal(), renamed the old get_diagonal() to get_diagonal_numpy(), and added a new get_diagonal() function that can select between the custom and numpy implementations. Also added a separate unit test class for the custom get_diagonal() function.

### CODE REVIEW

**Comment by kylemasc917** [comment]
@haiderabbas007 I  have added you as a reviewer for this request if you could do so as soon as possible so it may be merged. Thank you.

**Comment by kylemasc917** [comment]
@haiderabbas007 Please review this as soon as possible so this can be merged.

**Review by haiderabbas007 — APPROVED** [review]
Reviewed

**Comment by haiderabbas007** [comment]
Please let me know if anything else needs to be done

**Pull request merged**
