### PR TITLE
Included for loop implementation of Matrix Dot Product in CalculationTimeMatrixMultiplicationAndDotProduct.ipynb Jupyter notebook

### PR DESCRIPTION
**Pull request by ojha-aditya**
Included the implementation using for loop to calculate Dot Product in CalculationTimeMatrixMultiplicationAndDotProduct.ipynb

### CODE REVIEW

**Comment by kylemasc917** [comment]
@jkblc I have added you as a reviewer to this request if you could do so as soon as possible so it can be merged.

**Comment by kylemasc917** [comment]
@jkblc Please review this as soon as possible so this can be merged.

**Review by jkblc — CHANGES_REQUESTED** [review]
Please address the conflict first

**Comment by ojha-aditya** [comment]
Done, resolved the conflict.

**Review by jkblc — APPROVED** [review]
Looks good

**Pull request merged**
