### PR TITLE
Update the markdown documentation for Matrix Multiplication and Dot Product

### PR DESCRIPTION
**Pull request by ojha-aditya**
Added the execution time of Dot Product using for loops to the file containing benchmarks for Matrix Multiplication and Dot Product.

### CODE REVIEW

**Comment by kylemasc917** [comment]
@rappoccio I have added you as a reviewer to this pull request if you could do so as soon as possible so it can be merged.

**Comment by kylemasc917** [comment]
@SchrodingersStruggle I have added you as a reviewer to this request please do so as soon as possible so it can be merged.

**Comment by kylemasc917** [comment]
@SchrodingersStruggle Please review this as soon as possible so this can be merged.

**Comment by kylemasc917** [comment]
@zbpetersbuf I have added you as reviewer for this request

**Comment by ojha-aditya** [comment]
Resolved it.

**Review by zbpetersbuf — APPROVED** [review]
issue fixed, approved

**Pull request merged**
