### PR TITLE
Revert "Added the .devcontainer directory (to setup the codespace for Python)"

### PR DESCRIPTION
**Pull request by laserlab**
Reverts ubsuny/CP1-24-HW2#17

Since it adds an additional file that does not fit the description of the PR.

### CODE REVIEW

**Comment by laserlab** [comment]
@abruns123 @HeshamElsaman @kylemasc917 This PR had to be reverted since it contains a file (broadcasting) that does not fit the description of the original PR. This has to be fixed before it can be considered done.

**Comment by laserlab** [comment]
@abruns123 @HeshamElsaman any progress?

**Comment by HeshamElsaman** [comment]
I'm trying to see what I can do. It's my first time dealing with reverting a pull request.
I initially thought it shouldn't be I who reverts it, but I guess I could? Because I found a button called "revert".
Further, I was searching for how to revert merging while adding new edits (i.e., deleting the file then re-merging), and that's what I'm trying to do right now.
I found a suggestion to create a new local branch from the point prior to the point we want to revert, and then add the edits to those branch and then push the commits there. I've done that, I created a new branch, and technically didn't have to add any edits to it, I just need to push it (I guess?). However, although I did that and then clicked the revert button, I'm now stuck with no clear action to do. Should I just create another pull request then and that's it?

**Comment by HeshamElsaman** [comment]
Although I clicked that revert button, I see no changes to the remote main repository.

**Comment by HeshamElsaman** [comment]
Oh, I guess it's not just about clicking that button

**Comment by laserlab** [comment]
As we discussed there are a couple of options. If you want to merge this revert PR and then open a new PR with the correct file(s) do that. In this case @kylemasc917 can just merge this PR and then @abruns123 can review the new one.

**Comment by HeshamElsaman** [comment]
Yes, I do agree with that.
Please, @kylemasc917 , you can merge this and I'll open a new one

**Pull request merged**
