### PR TITLE
added my name to the task list

### PR DESCRIPTION
**Pull request by zbpetersbuf**
don't merge yet still working on coding

### CODE REVIEW

**Comment by zbpetersbuf** [comment]
now it could be accepted

**Comment by zbpetersbuf** [comment]
iamtomato761 its says you need to review this pull request before it can get merged, do you know why this is?

**Comment by zbpetersbuf** [comment]
So today is the last day I can realistically work on this since im traveling tomorrow and getting back Sunday, I could hopefully do some work on the plane if there's wifi but I not sure how realistic this is, so I would like to be able to merge this pull request, if there is anything needed of me please let me know

**Comment by laserlab** [comment]
> iamtomato761 its says you need to review this pull request before it can get merged, do you know why this is?

Use an @ sign in front of usernames to mention them and the y get a notification @iamtomato761 
PR must be reviewed by someone else and so I assigned @iamtomato761 to it since it is the same algorithm but task documentation

**Comment by laserlab** [comment]
> So today is the last day I can realistically work on this since im traveling tomorrow and getting back Sunday, I could hopefully do some work on the plane if there's wifi but I not sure how realistic this is, so I would like to be able to merge this pull request, if there is anything needed of me please let me know

@iamtomato761 Can you do that?

**Comment by laserlab** [comment]
@zbpetersbuf Could you clarify th difference between this PR and #48

**Pull request closed without merging**
