### PR TITLE
Added method to return the transpose of an array

### PR DESCRIPTION
**Pull request by jkblc**
Added method to return the transpose of an array in the matrix_operations file

### CODE REVIEW

**Comment by kylemasc917** [comment]
@dhamalakamal I have added you as a reviewer for this request. Please do so in a timely manner and I will merge this only upon your explicit approval.

**Comment by jkblc** [comment]
@laserlab I assume I can add numpy einsum in a future pull request?

**Comment by laserlab** [comment]
> @laserlab I assume I can add numpy einsum in a future pull request?

PR should be significant additions / deletions / changes. Your addition is basically ```return np.transpose(matrix)```

So please add it to this one as I originally stated. You can always do another PR only something related or unrelated.

**Comment by kylemasc917** [comment]
@jkblc Please address the comments made above as soon as possible so this can be merged

**Comment by kylemasc917** [comment]
@dhamalakamal Please review this as soon as possible so this can be merged.

**Comment by kylemasc917** [comment]
@ojha-aditya I have added you as reviewer for this request.

**Review by ojha-aditya — APPROVED** [review]
This looks good for merging.

**Pull request merged**
