### PR TITLE
Trace of an array

### PR DESCRIPTION
**Pull request by dhamalakamal**
This is just the theoretical part of Trace of an array with Enstein notation.

### CODE REVIEW

**Comment by kylemasc917** [comment]
I have added a reviewer for this pull request. I will merge it upon their approval.

**Comment by kylemasc917** [comment]
@dnxjay please review this when you are able. Thank you.

**Comment by laserlab** [comment]
@dhamalakamal  Before this can be merged you have to squash your commits and add a useful commit message!

**Comment by laserlab** [comment]
@dnxjay Please review!

**Comment by dnxjay** [comment]
> @dnxjay please review this when you are able. Thank you.

Review completed. I apologize for the delay

**Review by dnxjay — APPROVED** [review]

**Comment by laserlab** [comment]
@dhamalakamal Before this can be merged you have to squash your commits and add a useful commit message!

**Comment by dhamalakamal** [comment]
How do I squash commits?

**Comment by laserlab** [comment]
> How do I squash commits?

There are a couple of options. I would suggest a google search here to check which options makes most sense for your development system

**Comment by kylemasc917** [comment]
@dhamalakamal please make the necessary changes as outlined by @laserlab and then I will immediately merge this.

**Pull request closed without merging**
