### PR TITLE
Moved jupyter-notebooks to respective folder

### PR DESCRIPTION
**Pull request by ojha-aditya**
Moved CalculationTimeForMatrixMultiplicationAndDotProduct.ipynb and ArrayAxisSummation.ipynb to jupyter-notebooks folder and renamed every file to CamelCase.

### CODE REVIEW

**Comment by kylemasc917** [comment]
@iglesias-cardinale I added you to review this quickly if you could do so at your convenience I will merge this after.

**Review by iglesias-cardinale — COMMENTED** [review]
Before I approve I just want to be sure of exactly the changes were made. I think you consolidated the array axis summation and matrix multiplication files into one folder since they're both Jupyter Notebooks, but I think it might be wiser to  group them into folders based on their matrix operation. Like have one folder for matrix multiplication, one for diagonalization, etc. I'm open to this idea though, I just want to be sure that's what's happening.

I like the renaming of the files, that aligns with the style that @laserlab has taught us. 

Lastly, there seems to have been some restructuring of the folders already in the main repository. Does this conflict with that?

**Comment by ojha-aditya** [comment]
Yes I thought about both the formats of grouping, currently there seems no consensus through all PRs so I went with the existing style. 
Checked the restructuring, there is no conflict.

**Review by iglesias-cardinale — APPROVED** [review]
Everything looks good. Folder structure works.

**Comment by iglesias-cardinale** [comment]
There's a conflict that needs to be resolved but I'm not exactly sure how that works. @ojha-aditya, maybe you can resolve that prior to merging?

**Comment by kylemasc917** [comment]
Its saying the problem is with lines 26 -32 
 `<<<<<<< ojha-aditya-devbranch-patch-4


7. Matrix Dot Product using for loops: $p = -0.050622328426910654 \pm 0.0975347645791423;  A: 7.8932421200591 \times 10^{-8}$
(Note: for loop execution time appears nearly constant, however, it is significantly higher than the more prominent exponential algorithms in magnitude)
=======
>>>>>>> main`

**Comment by ojha-aditya** [comment]
Resolved now.

**Comment by kylemasc917** [comment]
Great, merging now.

**Comment by iglesias-cardinale** [comment]
How did you resolve it? I saw where the problem was but I don't know how these things work and wasn't sure exactly _what_ the problem was

**Comment by ojha-aditya** [comment]
It was mostly an indentation not being consistent issue between two versions of the same file from different time/branches (not exactly sure which). I just clicked the resolve button and changed the alignment, then merged that commit. I was not sure I could do that, I thought we need maintainer permission for doing that.

**Pull request merged**
