### PR TITLE
Vector Inner Product

### PR DESCRIPTION
**Pull request by abruns123**
This addition adds a file that runs the inner product of two vectors created from the vectorGen function in pVectorGenerator. It uses a loop, vdot, and einsum function to calculate the inner product and prints out that product along with the times it took for the inner product to be calculated.

### CODE REVIEW

**Comment by kylemasc917** [comment]
@ojha-aditya I have added you as reviewer for this request if you could do so at your convenience.

**Review by ojha-aditya — CHANGES_REQUESTED** [review]
The pVectorGenerator.py file executes correctly. However as the branch for this is to synced with the version containing a .devcontainer file, it does not read the Jupyter notebook as one and hence does not allow to execute it in codespace. Once that is fixed it is good to be merged.

**Comment by ojha-aditya** [comment]
Somehow I still get this error message when trying to open the innerProduct Jupyter notebook: 
'''
Unable to open 'innerProduct.ipynb'
Unexpected token 'i', "import num"... is not valid JSON
'''

Does it allow you to compile it properly @abruns123? Maybe I could be making a mistake.

**Comment by abruns123** [comment]
I think the main issue is that I initially just copy and pasted the code from my codespace. I've tried manually adjusting it to fit jupyter format though the preview still doesn't say that its a valid notebook. Is there some way to directly transfer a file from a codespace that I'm missing?

**Comment by abruns123** [comment]
@ojha-aditya

**Comment by ojha-aditya** [comment]
Yes, manually formatting any Jupyter notebook is difficult due to these kind of issues. One such example we discussed in #31.
I can not think of a better solution than to create a new Jupyter notebook using the codespace and committing that directly. Maybe @kylemasc917 could suggest a better workaround?

**Comment by kylemasc917** [comment]
That is unfortunately the best way I can think of at the moment unless anyone else can think of better.

**Comment by abruns123** [comment]
Ok, I made a new codespace and put my code from innerProduct in there. I'm now trying to commit that file to my Branch2, but I'm getting an error.

image

**Comment by abruns123** [comment]
Never mind, just found a fix

**Comment by abruns123** [comment]
@ojha-aditya 
Okay, it should be working as intended now.

**Comment by ojha-aditya** [comment]
Yeah this is something I had encountered during HW1, there is a detailed stack page discussing it https://stackoverflow.com/questions/71768999/how-to-merge-when-you-get-error-hint-you-have-divergent-branches-and-need-to-s

**Review by ojha-aditya — APPROVED** [review]
Perfect. Good to merge.

**Pull request merged**
