### PR TITLE
Array axis summations

### PR DESCRIPTION
**Pull request by p-pxmpo**
I added my jupiter notebook of my array axis summations, please review and merge.

### CODE REVIEW

**Comment by p-pxmpo** [comment]
added several comments to the code

**Comment by p-pxmpo** [comment]
added docstrings and more descriptive markdown lines

**Comment by p-pxmpo** [comment]
Also created a new folder to add both the array axis summations into one folder

**Comment by kylemasc917** [comment]
@HeshamElsaman I have added you as a reviewer to this request could you please review it as soon as possible so it can be merged please.

**Comment by kylemasc917** [comment]
I will merge this now those revisions can be a new pull request.

**Pull request merged**
