### PR TITLE
Diagonal return and some project boilerplate

### PR DESCRIPTION
**Pull request by avgagliardo**
Created some boilerplate dirs and stub files for the project.

Also added a bunch of TODOs for each task on the HW description.

Implemented the Diagonal Return task.

Started a .gitignore file and populated it with some basic info

### CODE REVIEW

**Comment by HeshamElsaman** [comment]
Can I add myself as a reviewer?
I just reviewed it and have some suggestions to discuss.

**Comment by HeshamElsaman** [comment]
Ok, here are my thoughts: I believe it would be better to adopt the following design for more clarity and organization and less conflicts

> Separate file for the needed imports
> Separate file per implementation
> Separate file per unit test
> Separate file to import each implementation in to import it only once in __main__
> Separate file for __main__
>> The separate file for __main__ should only prompt to call a specific functionality (either an implementation or a unit test)
>> I guess it might be more convenient as well to let the __main__ file distinguish between two modes (developing mode and user-interface mode)

I guess we can also extend this design to add separate folders as/if needed.

I believe we should follow similar architecture for future HWs, like using that same architecture but getting it adjusted just as needed

**Comment by avgagliardo** [comment]
> Ok, here are my thoughts: I believe it would be better to adopt the following design for more clarity and organization and less conflicts
> 
> 1. Separate file for the needed imports
> 2. Separate file per implementation
> 3. Separate file per unit test
> 4. Separate file to import each implementation in to import it only once in **main**
> 5. Separate file for **main**
> 6. The separate file for **main** should only prompt to call a specific functionality (either an implementation or a unit test)
> 7. I guess it might be more convenient as well to let the **main** file distinguish between two modes (developing mode and user-interface mode)
> 
> I guess we can also extend this design to add separate folders as/if needed.
> 
> I believe we should follow similar architecture for future HWs, like using that same architecture but getting it adjusted just as needed

I was actually using this architecture, but I flattened it for the sake of other people's ability to clearly import modules. I actually prefer a broken out project directory, but a lot of other people have trouble with it. If it's not going to be an issue, I can revert changes back to a module-based structure.

**Comment by avgagliardo** [comment]
> 1. Separate file for the needed imports

Imports shouldn't be decoupled from the files that utilize them.

**Comment by iglesias-cardinale** [comment]
I think we specifically need to utilize np.einsum (Einstein summation) to adhere to the homework task, https://github.com/ubsuny/CP1-24-HW2/blob/712496634a8e39ad8ae1bf7eb799b815de71d27d/README.md?plain=1#L3

I haven't actually tried this yet but I think that something like

```python
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

diagonal_elements = np.einsum('ii->i', matrix)

print(diagonal_elements)
```

would work.

**Comment by HeshamElsaman** [comment]
> If it's not going to be an issue, I can revert changes back to a module-based structure.

I guess it will be preferable so that each one would be working on his/her own files without resulting in any conflicts.

**Comment by HeshamElsaman** [comment]
> Imports shouldn't be decoupled from the files that utilize them. (They can, but at the loss of readability/general clarity)

Can't we somehow compensate for that, like through adding comments and/or docstrings?

**Comment by avgagliardo** [comment]
> > Imports shouldn't be decoupled from the files that utilize them. (They can, but at the loss of readability/general clarity)
> 
> Can't we somehow compensate for that, like through adding comments and/or docstrings?

In terms of developer experience, this probably won't make sense for this project. Since everyone is only going to be using Numpy (mostly) it would be easier and more straight forward to simply import their own np module rather than rely on a central file that holds all of the imports. If the project were more complex, I'd agree with you. 

I flattened the directory for the same reason, to simplify the DX for the rest of the class that will be writing code-- but if we want to start using python with standard best practices we can start by adopting a single naming convention for all of the project files.

**Comment by avgagliardo** [comment]
> I think we specifically need to utilize np.einsum (Einstein summation) to adhere to the homework task,
> 
> https://github.com/ubsuny/CP1-24-HW2/blob/712496634a8e39ad8ae1bf7eb799b815de71d27d/README.md?plain=1#L3
> 
> I haven't actually tried this yet but I think that something like
> 
> ```python
> matrix = np.array([[1, 2, 3],
>                    [4, 5, 6],
>                    [7, 8, 9]])
> 
> diagonal_elements = np.einsum('ii->i', matrix)
> 
> print(diagonal_elements)
> ```
> 
> would work.

I'm sorry I'm not sure I understand the context. Was this meant for another issue/PR?

**Comment by HeshamElsaman** [comment]
I believe that all the members should at least react to show their agreement with the architecture. Otherwise, we need to approve this PR as soon as possible to be able to utilize the suggested structure.

After discussing it, I agree with following that structure and I confirm its convenience.

The one minor comment I have is that we need to import the _timeit_ library I guess.

**Comment by avgagliardo** [comment]
We might need to message @iglesias-cardinale or assign another reviewer for the sake of getting this PR merged in a timely manner. 

I'll keep working on my local branch (using the above architecture design) in the meantime.

**Review by iglesias-cardinale — APPROVED** [review]
This looks good! We can use it as a framework to input the rest of the methods/time comparisons. The unit tests are also great. Merging to main.

**Comment by kylemasc917** [comment]
Sounds good to me. Merging

**Pull request merged**
