### PR TITLE
Python Code for Inner and Outer product

### PR DESCRIPTION
**Pull request by Priyanka-43**
I wrote python code to calculate inner and outer product by using two different methods. 
1. using numpy built in function
2. Numpy Einsum

### CODE REVIEW

**Comment by laserlab** [comment]
@Priyanka-43 Before this can be merged squash commits with the same commit message and use useful and descriptive commit messages

**Comment by Priyanka-43** [comment]
I think I am done with the code part. I am still having issues with my documentation part. I will take care of commits as well.

**Comment by laserlab** [comment]
> I think I am done with the code part. I am still having issues with my documentation part. I will take care of commits as well.

Also change the title of the pR to something useful.

**Comment by kylemasc917** [comment]
Once the above comments have been addressed, I will add a reviewer for this pull request.

**Comment by Priyanka-43** [comment]
@kylemasc917  Can you please tell me how to change the title of PR?

**Comment by Priyanka-43** [comment]
@kylemasc917 Hi, I have done the same. Can you please add the reviewer for pull request?

**Comment by kylemasc917** [comment]
You just need to squash the commits and then I will add a reviewer asap.

**Comment by kylemasc917** [comment]
@ojha-aditya I have added you as a reviewer for this request please review the code as submitted and once you approve and previous issues have been addressed, I will merge this asap.

**Review by ojha-aditya — APPROVED** [review]
The code and documentation work fine. Good to merge.

**Comment by kylemasc917** [comment]
From what I can find this requires you to download the GitHub desktop application. Once you have done that, I found this video to be helpful. https://youtu.be/_W2DoGeDALs?si=RfZVhMQdDDgL9K5X Feel free to message with further questions.

**Pull request merged**
