### PR TITLE
Random Vector Generator

### PR DESCRIPTION
**Pull request by abruns123**
This python file provides a function that creates a random vector with length, range of values of the elements, and percent chance of elements being complex under the control of the user.

I intend to import this function such that I may use it with separate files.

### CODE REVIEW

**Comment by kylemasc917** [comment]
Please add a label and milestone.

**Comment by kylemasc917** [comment]
@avgagliardo I have added you as reviewer for this request please do so as soon as possible so it can be merged.

**Comment by avgagliardo** [comment]
> @avgagliardo I have added you as reviewer for this request please do so as soon as possible so it can be merged.

checking it out now.

**Review by avgagliardo — COMMENTED** [review]
Code is well-formed and executes. 

Comments are present, but docstrings are missing. There are also minor linting issues.

Approving the PR to add the functionality, but future commits should include docstrings.

**Review by avgagliardo — APPROVED** [review]
Code is well-formed and executes.

Comments are present, but docstrings are missing. There are also minor linting issues.

Approving the PR to add the functionality, but future commits should include docstrings.

**Pull request merged**
