### PR TITLE
Added axis summation script

### PR DESCRIPTION
**Pull request by iglesias-cardinale**
I noticed nobody was assigned to implement axis summation so I wrote a quick script to do that using np.einsum and tested how the calculation time scaled with matrix size.

### CODE REVIEW

**Comment by kylemasc917** [comment]
That works for me feel free to review it I have added you now.

**Comment by kylemasc917** [comment]
Please add a label and milestone to this request

**Comment by ojha-aditya** [comment]
Added the label and milestone, will soon go through the PR.

**Comment by iglesias-cardinale** [comment]
Thank you for offering to review @ojha-aditya

**Review by ojha-aditya — CHANGES_REQUESTED** [review]
The code looks perfect, I just have the suggestion to remove the results cells before merging as discussed in the class and previous HW repository.

**Comment by iglesias-cardinale** [comment]
@ojha-aditya Just added the docstrings and cleared the results/cell outputs. Let me know if there's anything else!

**Review by ojha-aditya — APPROVED** [review]
Looks good for merging to me.

**Comment by kylemasc917** [comment]
I have merged it

**Pull request merged**
