### PR TITLE
Add script for time of matrix multiplication

### PR DESCRIPTION
**Pull request by iglesias-cardinale**
I wrote this script recently for another class. It multiplies NxN matrices together and times how long it takes to compute the multiplication. It does that for matrices of various sizes, plots the calculation time versus matrix size and uses scipy.optimize to find how computation time scales with size. It also does this for three different methods of multiplication: two built-in python methods and one hand written method. 

This could be easily adapted to include Einstein notation and extended to other matrix operations. It needs some documentation to describe what's going on.

### CODE REVIEW

**Comment by laserlab** [comment]
Looks good. When you adapt the code or the codespace so we can test it it could be your homework task. Not merging this now since we have no maintainer yet.

**Comment by avgagliardo** [comment]
I'll work on reviewing this today.

**Review by avgagliardo — APPROVED** [review]
After initializing a fresh codespace, I can confirm that this notebook executes on python 3.12.1 and has well-formed comments.

Future additions might include further docstrings and exception handling.

**Comment by kylemasc917** [comment]
I agree. I am merging this pull request and it can be edited by further pull requests in the future as needed.

**Comment by laserlab** [comment]
> After initializing a fresh codespace, I can confirm that this notebook executes on python 3.12.1 and has well-formed comments.
> 
> Future additions might include further docstrings and exception handling.

Agreed but can be done by someone else as well

**Pull request merged**
